# Generated by Django 5.0.4 on 2024-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_investorprofile_investor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
